In [152]:
import pandas as pd
import numpy as np

In [153]:
"""#reading the file using dask
import dask
import dask.dataframe as dd
from dask.delayed import delayed

parts = dask.delayed(pd.read_excel)("N:/15.11.2023 Data/dataexport_20231115T124544.xlsx")
data = dd.from_delayed(parts)

data.head()"""

'#reading the file using dask\nimport dask\nimport dask.dataframe as dd\nfrom dask.delayed import delayed\n\nparts = dask.delayed(pd.read_excel)("N:/15.11.2023 Data/dataexport_20231115T124544.xlsx")\ndata = dd.from_delayed(parts)\n\ndata.head()'

### 1. Readind in the data

In [154]:
data = pd.read_excel('N:/15.11.2023 Data/dataexport_20231115T124544.xlsx')

C:\Users\phall\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\openpyxl\styles\stylesheet.py:226: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

In [155]:
data.head()

,location,Basel,Basel.1,Basel.2,Basel.3,Basel.4,Basel.5,Basel.6,Basel.7,Basel.8,...,Basel.53,Basel.54,Basel.55,Basel.56,Basel.57,Basel.58,Basel.59,Basel.60,Basel.61,Basel.62
0,lat,47.75,47.75,47.75,47.75,47.75,47.75,47.75,47.75,47.75,...,47.75,47.75,47.75,47.75,47.75,47.75,47.75,47.75,47.75,47.75
1,lon,7.5,7.5,7.5,7.5,7.5,7.5,7.5,7.5,7.5,...,7.5,7.5,7.5,7.5,7.5,7.5,7.5,7.5,7.5,7.5
2,asl,363.65314,363.65314,363.65314,363.65314,363.65314,363.65314,363.65314,363.65314,363.65314,...,363.65314,363.65314,363.65314,363.65314,363.65314,363.65314,363.65314,363.65314,363.65314,363.65314
3,variable,Temperature,Growing Degree Days,Temperature,Temperature,Temperature,Temperature,Temperature,Precipitation Total,Relative Humidity,...,Soil Temperature,Soil Temperature,Soil Moisture,Soil Moisture,Soil Moisture,Soil Moisture,Soil Moisture Available To Plant,Soil Moisture Available To Plant,Soil Moisture Available To Plant,Soil Moisture Available To Plant
4,unit,°C,GDDc,°C,°C,°C,°C,°C,mm,%,...,°C,°C,m³/m³,m³/m³,m³/m³,m³/m³,fraction,fraction,fraction,fraction

### 2. Data Cleaning

First 4 rows(3 plus current heading) are the same thing which can be replaced

The data is from Basel(location) found at latitude=47.75 and longitude=7.5. Resolution is measured hourly with no aggregation

In [156]:
data = data.iloc[4:]

In [157]:
data = data.drop([5,7])
data.head()

,location,Basel,Basel.1,Basel.2,Basel.3,Basel.4,Basel.5,Basel.6,Basel.7,Basel.8,...,Basel.53,Basel.54,Basel.55,Basel.56,Basel.57,Basel.58,Basel.59,Basel.60,Basel.61,Basel.62
4,unit,°C,GDDc,°C,°C,°C,°C,°C,mm,%,...,°C,°C,m³/m³,m³/m³,m³/m³,m³/m³,fraction,fraction,fraction,fraction
6,resolution,hourly,hourly,hourly,hourly,hourly,hourly,hourly,hourly,hourly,...,hourly,hourly,hourly,hourly,hourly,hourly,hourly,hourly,hourly,hourly
8,timestamp,Basel Temperature [2 m elevation corrected],Basel Growing Degree Days [2 m elevation corre...,Basel Temperature [900 mb],Basel Temperature [850 mb],Basel Temperature [800 mb],Basel Temperature [700 mb],Basel Temperature [500 mb],Basel Precipitation Total,Basel Relative Humidity [2 m],...,Basel Soil Temperature [28-100 cm down],Basel Soil Temperature [100-255 cm down],Basel Soil Moisture [0-7 cm down],Basel Soil Moisture [7-28 cm down],Basel Soil Moisture [28-100 cm down],Basel Soil Moisture [100-255 cm down],Basel Soil Moisture Available To Plant [0-7 cm...,Basel Soil Moisture Available To Plant [7-28 c...,Basel Soil Moisture Available To Plant [28-100...,Basel Soil Moisture Available To Plant [100-25...
9,2000-01-01 00:00:00,1.550245,0,-0.34,-2.35,-4.99,-8.75,-23.01,0,93.43871,...,3.85,7.54,0.382,0.385,0.416,0.395,0.231,0.234,0.265,0.244
10,2000-01-01 01:00:00,1.500245,0,-0.3,-2.63,-4.67,-8.95,-22.71,0,93.29928,...,3.81,7.63,0.384,0.386,0.418,0.401,0.233,0.235,0.267,0.25

In [158]:
data.columns = data.iloc[2]
data = data.drop(8)
data = data.drop(6)

# After dropping the necessary rows, now we can rename the columns accordingly with their unit of measurent
# Drop the 'Basel ' prefix from all column names
data.columns = data.columns.str.replace('Basel ', '')

# Concatenate column names with row 1 values in brackets
data.columns = [f'{col} ({data.iloc[0][col]})' for col in data.columns]

# Drop the first row, as it's now included in the column names
data = data.iloc[1:]

# Now we reset the index of the dataframe
data.reset_index()

data.head()

,timestamp (unit),Temperature [2 m elevation corrected] (°C),Growing Degree Days [2 m elevation corrected] (GDDc),Temperature [900 mb] (°C),Temperature [850 mb] (°C),Temperature [800 mb] (°C),Temperature [700 mb] (°C),Temperature [500 mb] (°C),Precipitation Total (mm),Relative Humidity [2 m] (%),...,Soil Temperature [28-100 cm down] (°C),Soil Temperature [100-255 cm down] (°C),Soil Moisture [0-7 cm down] (m³/m³),Soil Moisture [7-28 cm down] (m³/m³),Soil Moisture [28-100 cm down] (m³/m³),Soil Moisture [100-255 cm down] (m³/m³),Soil Moisture Available To Plant [0-7 cm down] (fraction),Soil Moisture Available To Plant [7-28 cm down] (fraction),Soil Moisture Available To Plant [28-100 cm down] (fraction),Soil Moisture Available To Plant [100-255 cm down] (fraction)
9,2000-01-01 00:00:00,1.550245,0,-0.34,-2.35,-4.99,-8.75,-23.01,0,93.43871,...,3.85,7.54,0.382,0.385,0.416,0.395,0.231,0.234,0.265,0.244
10,2000-01-01 01:00:00,1.500245,0,-0.3,-2.63,-4.67,-8.95,-22.71,0,93.29928,...,3.81,7.63,0.384,0.386,0.418,0.401,0.233,0.235,0.267,0.25
11,2000-01-01 02:00:00,1.470245,0,-0.18,-2.75,-4.52,-8.63,-22.79,0,93.43304,...,3.8,7.63,0.384,0.385,0.418,0.401,0.233,0.234,0.267,0.25
12,2000-01-01 03:00:00,1.880245,0,-0.15,-2.77,-4.37,-8,-22.85,0,93.80152,...,3.8,7.63,0.384,0.385,0.418,0.401,0.233,0.234,0.267,0.25
13,2000-01-01 04:00:00,2.310246,0,-0.29,-2.74,-4.44,-7.59,-22.62,0,93.96607,...,3.79,7.62,0.384,0.385,0.417,0.401,0.233,0.234,0.266,0.25

In [159]:
data.columns

Index(['timestamp (unit)', 'Temperature [2 m elevation corrected] (°C)',
       'Growing Degree Days [2 m elevation corrected] (GDDc)',
       'Temperature [900 mb] (°C)', 'Temperature [850 mb] (°C)',
       'Temperature [800 mb] (°C)', 'Temperature [700 mb] (°C)',
       'Temperature [500 mb] (°C)', 'Precipitation Total (mm)',
       'Relative Humidity [2 m] (%)', 'Snowfall Amount (cm)', 'Snow Depth (m)',
       'Wind Gust (km/h)', 'Wind Speed [10 m] (km/h)',
       'Wind Direction [10 m] (°)', 'Wind Speed [100 m] (km/h)',
       'Wind Direction [100 m] (°)', 'Wind Speed [900 mb] (km/h)',
       'Wind Direction [900 mb] (°)', 'Wind Speed [850 mb] (km/h)',
       'Wind Direction [850 mb] (°)', 'Wind Speed [800 mb] (km/h)',
       'Wind Direction [800 mb] (°)', 'Wind Speed [700 mb] (km/h)',
       'Wind Direction [700 mb] (°)', 'Wind Speed [500 mb] (km/h)',
       'Wind Direction [500 mb] (°)', 'Wind Speed [250 mb] (km/h)',
       'Wind Direction [250 mb] (°)', 'Cloud Cover Total (%)',
       'Cloud Cover High [high cld lay] (%)',
       'Cloud Cover Medium [mid cld lay] (%)',
       'Cloud Cover Low [low cld lay] (%)', 'CAPE [180-0 mb above gnd] (J/kg)',
       'Sunshine Duration (min)', 'Shortwave Radiation (W/m²)',
       'Longwave Radiation (W/m²)', 'UV Radiation (W/m²)',
       'Direct Shortwave Radiation (W/m²)',
       'Diffuse Shortwave Radiation (W/m²)',
       'Mean Sea Level Pressure [MSL] (hPa)',
       'Geopotential Height [1000 mb] (Gpm)',
       'Geopotential Height [850 mb] (Gpm)',
       'Geopotential Height [800 mb] (Gpm)',
       'Geopotential Height [700 mb] (Gpm)',
       'Geopotential Height [500 mb] (Gpm)', 'Evapotranspiration (mm)',
       'Potential Evaporation (mm)',
       'FAO Reference Evapotranspiration [2 m] (mm)',
       'Vapor Pressure Deficit [2 m] (hPa)', 'PBL Height (m)',
       'Temperature (°C)', 'Soil Temperature [0-7 cm down] (°C)',
       'Soil Temperature [7-28 cm down] (°C)',
       'Soil Temperature [28-100 cm down] (°C)',
       'Soil Temperature [100-255 cm down] (°C)',
       'Soil Moisture [0-7 cm down] (m³/m³)',
       'Soil Moisture [7-28 cm down] (m³/m³)',
       'Soil Moisture [28-100 cm down] (m³/m³)',
       'Soil Moisture [100-255 cm down] (m³/m³)',
       'Soil Moisture Available To Plant [0-7 cm down] (fraction)',
       'Soil Moisture Available To Plant [7-28 cm down] (fraction)',
       'Soil Moisture Available To Plant [28-100 cm down] (fraction)',
       'Soil Moisture Available To Plant [100-255 cm down] (fraction)'],
      dtype='object')

In [160]:
# Rename the first column of the dataset from 'Timestamp Unit' to just 'Timestamp'
data = data.rename(columns={"timestamp (unit)": "Timestamp"})

In [161]:
data.tail()

,Timestamp,Temperature [2 m elevation corrected] (°C),Growing Degree Days [2 m elevation corrected] (GDDc),Temperature [900 mb] (°C),Temperature [850 mb] (°C),Temperature [800 mb] (°C),Temperature [700 mb] (°C),Temperature [500 mb] (°C),Precipitation Total (mm),Relative Humidity [2 m] (%),...,Soil Temperature [28-100 cm down] (°C),Soil Temperature [100-255 cm down] (°C),Soil Moisture [0-7 cm down] (m³/m³),Soil Moisture [7-28 cm down] (m³/m³),Soil Moisture [28-100 cm down] (m³/m³),Soil Moisture [100-255 cm down] (m³/m³),Soil Moisture Available To Plant [0-7 cm down] (fraction),Soil Moisture Available To Plant [7-28 cm down] (fraction),Soil Moisture Available To Plant [28-100 cm down] (fraction),Soil Moisture Available To Plant [100-255 cm down] (fraction)
209284,2023-11-15 19:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
209285,2023-11-15 20:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
209286,2023-11-15 21:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
209287,2023-11-15 22:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
209288,2023-11-15 23:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [162]:
data.shape

(209280, 64)

In [163]:
data.isnull().sum()

Timestamp                                                          0
Temperature [2 m elevation corrected] (°C)                       191
Growing Degree Days [2 m elevation corrected] (GDDc)             191
Temperature [900 mb] (°C)                                        191
Temperature [850 mb] (°C)                                        191
                                                                ...
Soil Moisture [100-255 cm down] (m³/m³)                          191
Soil Moisture Available To Plant [0-7 cm down] (fraction)        191
Soil Moisture Available To Plant [7-28 cm down] (fraction)       191
Soil Moisture Available To Plant [28-100 cm down] (fraction)     191
Soil Moisture Available To Plant [100-255 cm down] (fraction)    191
Length: 64, dtype: int64

In [164]:
# 209280-191 = 209089
print(data.iloc[209088])

Timestamp                                                        2023-11-08 00:00:00
Temperature [2 m elevation corrected] (°C)                                  5.160245
Growing Degree Days [2 m elevation corrected] (GDDc)                               0
Temperature [900 mb] (°C)                                                       2.84
Temperature [850 mb] (°C)                                                      -0.26
                                                                        ...
Soil Moisture [100-255 cm down] (m³/m³)                                        0.301
Soil Moisture Available To Plant [0-7 cm down] (fraction)                      0.227
Soil Moisture Available To Plant [7-28 cm down] (fraction)                     0.222
Soil Moisture Available To Plant [28-100 cm down] (fraction)                   0.127
Soil Moisture Available To Plant [100-255 cm down] (fraction)                   0.15
Name: 209097, Length: 64, dtype: object

This suggests that the last 191 tuples are just null valued, so we drop the last 191 rows

In [165]:
data = data.iloc[:-191]
data.tail()

,Timestamp,Temperature [2 m elevation corrected] (°C),Growing Degree Days [2 m elevation corrected] (GDDc),Temperature [900 mb] (°C),Temperature [850 mb] (°C),Temperature [800 mb] (°C),Temperature [700 mb] (°C),Temperature [500 mb] (°C),Precipitation Total (mm),Relative Humidity [2 m] (%),...,Soil Temperature [28-100 cm down] (°C),Soil Temperature [100-255 cm down] (°C),Soil Moisture [0-7 cm down] (m³/m³),Soil Moisture [7-28 cm down] (m³/m³),Soil Moisture [28-100 cm down] (m³/m³),Soil Moisture [100-255 cm down] (m³/m³),Soil Moisture Available To Plant [0-7 cm down] (fraction),Soil Moisture Available To Plant [7-28 cm down] (fraction),Soil Moisture Available To Plant [28-100 cm down] (fraction),Soil Moisture Available To Plant [100-255 cm down] (fraction)
209093,2023-11-07 20:00:00,6.510245,0,3.29,0.06,-3.67,-10.72,-29.82,0,87.41894,...,11.96,16.48,0.38,0.372,0.276,0.301,0.229,0.221,0.125,0.15
209094,2023-11-07 21:00:00,5.970245,0,3.32,0.02,-3.66,-10.71,-29.7,0,89.29355,...,11.95,16.48,0.379,0.372,0.276,0.301,0.228,0.221,0.125,0.15
209095,2023-11-07 22:00:00,5.700245,0,3.25,-0.12,-3.59,-10.49,-29.43,0,89.710396,...,11.94,16.47,0.378,0.372,0.276,0.301,0.227,0.221,0.125,0.15
209096,2023-11-07 23:00:00,5.450245,0,3.35,-0.21,-3.33,-10.01,-29.65,0,89.9415,...,11.94,16.47,0.379,0.373,0.278,0.301,0.228,0.222,0.127,0.15
209097,2023-11-08 00:00:00,5.160245,0,2.84,-0.26,-3.53,-10.65,-29.05,0,89.97886,...,11.92,16.47,0.378,0.373,0.278,0.301,0.227,0.222,0.127,0.15

In [166]:
data.isnull().sum()

Timestamp                                                        0
Temperature [2 m elevation corrected] (°C)                       0
Growing Degree Days [2 m elevation corrected] (GDDc)             0
Temperature [900 mb] (°C)                                        0
Temperature [850 mb] (°C)                                        0
                                                                ..
Soil Moisture [100-255 cm down] (m³/m³)                          0
Soil Moisture Available To Plant [0-7 cm down] (fraction)        0
Soil Moisture Available To Plant [7-28 cm down] (fraction)       0
Soil Moisture Available To Plant [28-100 cm down] (fraction)     0
Soil Moisture Available To Plant [100-255 cm down] (fraction)    0
Length: 64, dtype: int64

Now that there are no more null values, we then have to seperate the Timestamp column into data and time

In [167]:
data['Timestamp'] = pd.to_datetime(data['Timestamp'])
data['Date'], data['Time'] = data['Timestamp'].dt.normalize(), data['Timestamp'].dt.time
data = data.drop('Timestamp', axis=1)

# Move the two new columns to the begining of the dataframe
data = data[['Date', 'Time'] + [col for col in data.columns if col not in ['Date', 'Time']]]

data.head()

,Date,Time,Temperature [2 m elevation corrected] (°C),Growing Degree Days [2 m elevation corrected] (GDDc),Temperature [900 mb] (°C),Temperature [850 mb] (°C),Temperature [800 mb] (°C),Temperature [700 mb] (°C),Temperature [500 mb] (°C),Precipitation Total (mm),...,Soil Temperature [28-100 cm down] (°C),Soil Temperature [100-255 cm down] (°C),Soil Moisture [0-7 cm down] (m³/m³),Soil Moisture [7-28 cm down] (m³/m³),Soil Moisture [28-100 cm down] (m³/m³),Soil Moisture [100-255 cm down] (m³/m³),Soil Moisture Available To Plant [0-7 cm down] (fraction),Soil Moisture Available To Plant [7-28 cm down] (fraction),Soil Moisture Available To Plant [28-100 cm down] (fraction),Soil Moisture Available To Plant [100-255 cm down] (fraction)
9,2000-01-01,00:00:00,1.550245,0,-0.34,-2.35,-4.99,-8.75,-23.01,0,...,3.85,7.54,0.382,0.385,0.416,0.395,0.231,0.234,0.265,0.244
10,2000-01-01,01:00:00,1.500245,0,-0.3,-2.63,-4.67,-8.95,-22.71,0,...,3.81,7.63,0.384,0.386,0.418,0.401,0.233,0.235,0.267,0.25
11,2000-01-01,02:00:00,1.470245,0,-0.18,-2.75,-4.52,-8.63,-22.79,0,...,3.8,7.63,0.384,0.385,0.418,0.401,0.233,0.234,0.267,0.25
12,2000-01-01,03:00:00,1.880245,0,-0.15,-2.77,-4.37,-8,-22.85,0,...,3.8,7.63,0.384,0.385,0.418,0.401,0.233,0.234,0.267,0.25
13,2000-01-01,04:00:00,2.310246,0,-0.29,-2.74,-4.44,-7.59,-22.62,0,...,3.79,7.62,0.384,0.385,0.417,0.401,0.233,0.234,0.266,0.25

### 3. Explanatory Data Analysis

### 4. Feature Selection